# Generated by Django 2.1.7 on 2019-02-27 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDetaillls',
            new_name='ContactDetails',
        ),
    ]
